on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check.yaml

permissions:
  contents: read

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macos-latest, r: "release" }
          - { os: windows-latest, r: "release" }
          - { os: ubuntu-latest, r: "devel", http-user-agent: "release" }
          - { os: ubuntu-latest, r: "release" }
          - { os: ubuntu-latest, r: "oldrel-1" }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      # macOS + Linux: install Eigen and expose to compiler
      - name: Install system dependencies for Linux/macOS
        if: runner.os != 'Windows'
        run: |
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            brew update
            brew install pkg-config proj gdal eigen
            mkdir -p ~/.R
            echo 'CXXFLAGS += -I/opt/homebrew/include/eigen3' >> ~/.R/Makevars
          else
            sudo apt-get update
            sudo apt-get install -y libeigen3-dev
            mkdir -p ~/.R
            echo 'CXXFLAGS += -I/usr/include/eigen3' >> ~/.R/Makevars
          fi

      # Windows: expose Eigen headers from Rtools path
      - name: Install Eigen for TMB on Windows
        if: runner.os == 'Windows'
        run: |
          echo "R_MAKEVARS_USER=${HOME}\\Documents\\.R\\Makevars.win" >> $GITHUB_ENV
          mkdir -p "${HOME}\\Documents\\.R"
          echo "CXXFLAGS += -I\"C:/rtools43/x86_64-w64-mingw32/include/eigen3\"" > "${HOME}\\Documents\\.R\\Makevars.win"

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: truenomad/AgePopDenom
